version: '3.9'
services:
  db:
    build: ./build_mysql_image/
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    
  mlflow:
    tty: true
    build: ./build_mlflow_image/
    ports:
      - "8090:8080"
      - "5010:5000"
    depends_on:
      db:
        condition: service_started

networks:
  default:
    name: mlflow-tracking-server-network
    external: true