version: '3.9'
services:
  db:
    build: ./build_mysql_image/
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"

  mlflow-artifact-server:
    build: ./build_mlflow_image/
    expose:
      - "5500"
    ports:
      - "5500:5500"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5500
      --artifacts-destination ./mlartifacts
      --gunicorn-opts "--log-level debug"
      --serve-artifacts
      --artifacts-only
    
  mlflow:
    tty: true
    build: ./build_mlflow_image/
    ports:
      - "5010:5000"
    depends_on:
      db:
        condition: service_started

    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri mysql+pymysql://'mlflow':'mlflow'@db:3306/mlflowruns
      --default-artifact-root http://127.0.0.1:5500/api/2.0/mlflow-artifacts/artifacts/experiments
      --gunicorn-opts "--log-level debug"

# networks:
#   default:
#     name: mlflow-tracking-server-network
#     external: true