version: '3.9'
services:
  db:
    image: mysql
    networks:
      - shared_network
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # MYSQL_DATABASE: mlflowruns
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3316:3306"
    volumes:
      - type: bind
        source: ./my.cnf
        target: /etc/my.cnf
      - ~/container_volume_persist/mysql-data-persist:/var/lib/mysql

  mlflow-artifact-server:
    build: .
    networks:
      - shared_network
    expose:
      - "5500"
    ports:
      - "5500:5500"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5500
      --artifacts-destination ./mlartifacts
      --gunicorn-opts "--log-level debug"
      --serve-artifacts
      --artifacts-only
    volumes:
      - ~/container_volume_persist/artifact-data-persist:/app/mlartifacts

  mlflow:
    tty: true
    build: .
    networks:
      - shared_network
    ports:
      - "5011:5001"

    # network_mode: "host"

    env_file:
      - .env

    command: >
      mlflow server
      --host 0.0.0.0
      --port 5001
      --backend-store-uri mysql+pymysql://'${MLFLOW_BACKEND_DB_USERNAME}':'${MLFLOW_BACKEND_DB_PASSWORD}'@${MLFLOW_BACKEND_URL}:3316/${MLFLOW_BACKEND_DB}
      --default-artifact-root http://${MLFLOW_ARTIFACT_URL}:5500/api/2.0/mlflow-artifacts/artifacts/experiments
      --gunicorn-opts "--log-level debug"

networks:
  shared_network:
    external: true
    
  # minio:
  #   build: ./build-minio
  #   expose:
  #     - "9000"
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   environment:
  #     MINIO_ROOT_USER: mlflowminio
  #     MINIO_ROOT_PASSWORD: mlflowminio
  #   command: >
  #     minio server /data --console-address ":9090"