name: Docker Compose Tests

on:
  push:
  pull_request:

env:
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker-compose --version

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=mockpassword" >> ./backend-storage/.env
          echo "MYSQL_DATABASE=mockdatabase" >> ./backend-storage/.env
          echo "MYSQL_USER=mockuser" >> ./backend-storage/.env
          echo "MYSQL_PASSWORD=mockuserpassword" >> ./backend-storage/.env
          echo "MLFLOW_BACKEND_DB_USERNAME=mockuser" >> ./backend-storage/.env
          echo "MLFLOW_BACKEND_DB_PASSWORD=mockpassword" >> ./backend-storage/.env
          echo "MLFLOW_BACKEND_URL=mockdb" >> ./backend-storage/.env
          echo "MLFLOW_BACKEND_DB=mockdatabase" >> ./backend-storage/.env
          echo "MLFLOW_ARTIFACT_URL=mockartifactserver" >> ./backend-storage/.env

      - name: Build and run tests
        run: |
          docker-compose -f ./backend-storage/docker-compose.yaml build --abort-on-container-exit
          docker-compose -f ./backend-storage/docker-compose.yaml up -d

      - name: Stop containers
        run: |
          docker-compose -f ./backend-storage/docker-compose.yaml down 