name: Docker Compose Tests

on:
  - push
  - pull_request

env:
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run tests
        run: |
          docker-compose -f ./backend-storage/docker-compose.yaml build --abort-on-container-exit
          docker-compose -f ./backend-storage/docker-compose.yaml up 
          docker-compose -f ./backend-storage/docker-compose.yaml down 
